# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overridden by the Spring profile you use,
# for example gateway-dev.yml if you use the "dev" profile.
#
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

eureka:
    client:
        enabled: true
        healthcheck:
            enabled: true
        fetch-registry: true
        register-with-eureka: true
        instance-info-replication-interval-seconds: 10
        registry-fetch-interval-seconds: 10
    instance:
        appname: uaa-service
        instanceId: uaa-service:${spring.application.instance-id:${random.value}}
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
        status-page-url-path: ${management.context-path}/info
        health-check-url-path: ${management.context-path}/health
        metadata-map:
            zone: primary # This is needed for the load balancer
            profile: ${spring.profiles.active}

ribbon:
    eureka:
        enabled: true

management:
    security:
        roles: ADMIN
    context-path: /management

spring:
    application:
        name: uaa-service
    profiles:
        active: @activatedProperties@
    mail:
        password: Dhm-sendgrid@18!
        host: smtp.sendgrid.net
        port: 587
        username: dhm-it
        protocol: smtp
        properties:
            starttls.enable: true
            auth: true

security:
    basic:
        enabled: false

discovery:
    password: admin

# ===================================================================
# Application specific properties
# Add your own application properties here
# ===================================================================

application:
    jwt:
        secret: my-secret
        # Token is valid 24 hours
        token-validity-in-seconds: 86400
        # Token for remember me is valid 30 days
        token-validity-in-seconds-for-remember-me: 2592000
    email:
        from: dhm-it
